### ISSUE TITLE
IP to ASN mapping for edge providers - difference with Cymru

### ISSUE THREAD

**Issue by qblone** [hadiasghari/pyasn#16] opened 2015-09-17 14:39 UTC
Pyasn provides AS1103 for IP:192.87.158.242 with prefix 192.87.0.0/16 when using ipasn_20150825.dat. This is the AS for Surfnet. Upon contacting Surfnet, they stated that they are the ISP for this range but it belongs to a customer of theirs,  WKAPNET with AS1142 being the correct answer. (They aggregate it to /16 to advertise in BGP).  

Team Cymru  (http://asn.cymru.com/cgi-bin/whois.cgi) correctly identifies the AS; However RIPE, domaintools, maxmind and CAIDA all give the same answer as pyasn. Perhaps Team-Cymru supplements this with WHOIS registry information.

**Comment by qblone** [comment] 2015-09-17 14:42
Some other cases where AS in BGP and  then team-cymru are:
(' 209.11.233.202', ‘31812’) has two registered ASN (22243, 31812). BGP maps it to AS22243 which is also upstream provider. 
('182.19.13.5', '38266’), similar to previous case this prefix has two ASNS (38266, 55410) in whois data.  BGP mapped it to 55410, which is also upstream provider for AS 38266

**Comment by hadiasghari** [comment] 2015-09-17 14:58
Thanks qblone, I'll check into these. One of our unit-tests also noted a few differences with Team Cymru look up results, but we couldn't pinpoint the cause; it's great that you have ISP confirmation for the first IP address. Our hunch was that the difference lies in different BGP-views (where the BGP-data is collected), or in processing the BGP-AS-path. It might be as you say also that they supplement their data from other sources. I'll provide more information.

**Comment by imaia** [comment] 2016-04-05 17:04
cymru now returns AS1103 as Surfnet, by the way.

**Comment by hadiasghari** [comment] 2016-09-30 22:52
thanks @imaia , I'm closing this issue then.

**Closed by hadiasghari** 2016-09-30 22:52 UTC
Labels: question
